repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
        - id: check-added-large-files

    - repo: https://github.com/PyCQA/flake8
      rev: 6.1.0
      hooks:
      -   id: flake8
          additional_dependencies: [
              'flake8-blind-except',
              'flake8-bugbear',
              'flake8-comprehensions',
              'flake8-implicit-str-concat',
              'pydocstyle>=5.0.0',
          ]

    - repo: https://github.com/psf/black
      rev: 23.7.0
      hooks:
        - id: black
        
    - repo: https://github.com/myint/docformatter
      rev: v1.7.5
      hooks:
        - id: docformatter
          args: [
            --in-place,
            --wrap-summaries,
            "88",
            --wrap-descriptions,
            "88",
          ]
